fix: added sorting to rofi refactor: faster selection for video links feat: added useful exit messages fix: removed & from players style: used | as delimiter to sed

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -4,7 +4,7 @@
 # UI
 
 external_menu() {
-	rofi -dmenu -i -width 1500 -p "$*"
+	rofi -sort -dmenu -i -width 1500 -p "$*"
 }
 
 launcher() {
@@ -93,27 +93,17 @@ generate_link() {
 	[ -n "$provider_id" ] && get_links "$provider_id"
 }
 
-select_quality () {
+select_quality() {
+	links=$(cat "$cache_dir"/* | sed 's|^Mp4-||g' | sort -g -r)
 	case "$1" in
-	best)
-		result=$(cat "$cache_dir"/* | head -n1)
-		for qual in 1080 720 480 360 240 144; do
-			result_fixed=$(cat "$cache_dir"/* | grep -m 1 "$qual")
-			[ -n "$result_in" ] && result="$result_fixed" && break
-		done
+	best) result=$(printf "%s\n" "$links" | head -n1)
 		;;
-	worst)
-		result=$(cat "$cache_dir"/* | tail -n1)
-		for qual in 144 270 360 480 720 1080; do
-			result_fixed=$(cat "$cache_dir"/* | grep -m 1 "$qual")
-			[ -n "$result_in" ] && result="$result_fixed" && break
-		done
+	worst) result=$(printf "%s\n" "$links" | grep -E '^[0-9]{3,4}p' | tail -n1)
 		;;
-	*)
-		result=$(cat "$cache_dir"/* | grep -m 1 "$1")
+	*) result=$(printf "%s\n" "$links" | grep -m 1 "$1")
 		;;
 	esac
-	[ -z "$result" ] && printf "Specified quality not found, defaulting to best" 1>&2 && result=$(cat "$cache_dir"/* | head -n1)
+	[ -z "$result" ] && printf "Specified quality not found, defaulting to best" 1>&2 && result=$(printf "%s\n" "$links" | head -n1)
 	printf "%s" "$result" | cut -d'>' -f2
 }
 
@@ -150,10 +140,10 @@ episodes_list() {
 
 download () {
 	case $1 in
-		*m3u8*)
-			ffmpeg -loglevel error -stats -i "$1" -c copy "$download_dir/$2.mp4" ;;
-		*)
-			aria2c --check-certificate=false --summary-interval=0 -x 16 -s 16 "$1" --dir="$download_dir" -o "$2.mp4" --download-result=hide ;;
+	*m3u8*)
+		ffmpeg -loglevel error -stats -i "$1" -c copy "$download_dir/$2.mp4" ;;
+	*)
+		aria2c --check-certificate=false --summary-interval=0 -x 16 -s 16 "$1" --dir="$download_dir" -o "$2.mp4" --download-result=hide ;;
 	esac
 }
 
@@ -167,13 +157,13 @@ play_episode() {
 		printf "Selected link:\n%s\n" "$episode"
 		;;
 	mpv | iina)
-		nohup "$player_function" --force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" > /dev/null &
+		nohup "$player_function" --force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" > /dev/null 2>&1
 		;;
 	vlc)
-		nohup "$player_function" --video-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" > /dev/null &
+		nohup "$player_function" --video-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" > /dev/null 2>&1
 		;;
 	syncplay)
-		nohup "$player_function" "$episode" -- --force-media-title="${allanime_title}episode-${ep_no}-${mode}" > /dev/null &
+		nohup "$player_function" "$episode" -- --force-media-title="${allanime_title}episode-${ep_no}-${mode}" > /dev/null 2>&1
 		;;
 	download)
 		"$player_function" "$episode" "${allanime_title}episode-${ep_no}-${mode}"
@@ -199,6 +189,7 @@ cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/ani-cli"
 [ ! -d "$cache_dir" ] && mkdir -p "$cache_dir"
 log_dir="${XDG_STATE_HOME:-$HOME/.local/state}/ani-cli"
 [ ! -d "$log_dir" ] && mkdir -p "$log_dir"
+
 # searching
 query="$*"
 while [ -z "$query" ]; do
@@ -212,20 +203,21 @@ title=$(printf "%s" "$result" | cut -f2)
 allanime_title="$(printf "%s" "$title" | cut -d'(' -f1 | tr -d '[:punct:]' | tr 'A-Z ' 'a-z-')"
 id=$(printf "%s" "$result" | cut -f1)
 ep_list=$(episodes_list "$id")
-ep_no=$(printf "%s" "$ep_list" | nth "Select episode: ") || exit 1
+ep_no=$(printf "%s" "$ep_list" | nth "Select episode: ") || die "Out of range"
+
 # playback & loop
 play_episode
 while cmd=$(printf "quit\nselect\nprevious\nreplay\nnext" | nth "Playing episode $ep_no of $title... "); do
 	case "$cmd" in
 	previous)
-		ep_no=$(printf "%s" "$ep_list" | sed -n "/^${ep_no}$/{n;p;}") 2>/dev/null
+		ep_no=$(printf "%s" "$ep_list" | sed -n "|^${ep_no}$|{n;p;}") 2>/dev/null
 		;;
 	replay) ;;
 	next)
-		ep_no=$(printf "%s" "$ep_list" | sed -n "/^${ep_no}$/{g;1!p;};h") 2>/dev/null
+		ep_no=$(printf "%s" "$ep_list" | sed -n "|^${ep_no}$|{g;1!p;};h") 2>/dev/null
 		;;
 	select)
-		ep_no=$(printf "%s" "$ep_list" | nth "Select episode: ") || exit 1
+		ep_no=$(printf "%s" "$ep_list" | nth "Select episode: ") || die "Out of range"
 		;;
 	*)
 		exit 0
